url_base: "https://www.metmuseum.org/art/collection/search?showOnly=withImage&department=11"
headers:
  Accept: "*/*"
  User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
output_folder: "Save_Data/Arts_Data"
proxy_list:
  - {"ip": "s-18346.sp2.ovh", "port": 11001, "country_code": "CZ", "username": "jTphN8YKiI_0", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11002, "country_code": "CZ", "username": "jTphN8YKiI_1", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11003, "country_code": "CZ", "username": "jTphN8YKiI_2", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11004, "country_code": "CZ", "username": "jTphN8YKiI_3", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11005, "country_code": "CZ", "username": "jTphN8YKiI_4", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11006, "country_code": "CY", "username": "jTphN8YKiI_5", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11007, "country_code": "CY", "username": "jTphN8YKiI_6", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11008, "country_code": "FR", "username": "jTphN8YKiI_7", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11009, "country_code": "FR", "username": "jTphN8YKiI_8", "password": "kV7JwDpIJXuc"}
  - {"ip": "s-18346.sp2.ovh", "port": 11010, "country_code": "DK", "username": "jTphN8YKiI_9", "password": "kV7JwDpIJXuc"}
total_pages: 67
log_dir: "Logs"
log_level: "DEBUG"
max_retries: 3
retry_delay: 5
min_request_delay: 1
max_request_delay: 3