version: '3.8'

services:
  scraper:
    build: .
    container_name: metmuseum_scraper
    volumes:
      - ./Save_Data:/app/Save_Data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
