version: '3.8'

services:
  scraper:
    build: .
    container_name: metmuseum_scraper
    volumes:
      - ./Save_Data:/app/Save_Data
      - ./Logs:/app/Logs 
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped